### PR TITLE
Added `$defaultContent` constructor parameter to `InMemoryFileFetcher`

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Review by gbirke — APPROVED** [review]
Default content is a nice feature, but why limit it to `InMemoryFileFetcher`? I guess it's because that class is only used for testing and having default values is also mostly useful for testing. Still, I think it might be useful to have a `DefaultValueDecoratorFileFetcher`.

**Comment by JeroenDeDauw** [comment]
What would this `DefaultValueDecoratorFileFetcher` look like? Would it catch errors from the decorated fetcher, and return the default value instead?

Anyway, a decorator might be a nice addition, though would not provide as nice of an API for the typical cases where you need this behavior.

I suppose you could do it the other way round as well... instead of having the InMemory thing on its own, have an `InMemoryDecoratorInterceptor` (idk what would be a sane name here) that checks if the provided URL is in the list, if so returns the corresponding value, and if not, forewards to the decorated object (ie a StubFetcher for the simple defaulting case). I've never created such a decorator AFAIK and it does seem a bit odd.

**Comment by gbirke** [comment]
I'd have gone with the error-catching decorator that returns a default value.

Your comment gives me another idea: A `ChainableFileFetcher` that gets a list of file fetchers and tries to fetch from each one until there is no exception or the list is exhausted. When the last in list is a stub that always returns the same thing, you avoid exceptions.

I agree with you on the "nice API" part, so maybe those fancy fetchers are overengineering it, when in reality this library is mostly about wrapping `get_file_contents` calls to make things testable.

**Comment by JeroenDeDauw** [comment]
Well yeah... `ChainableFileFetcher` sounds cool from a production code perspective, but then, you really want to be using a proper library for that part. (You can still use FileFetcher ofcourse, with an adapter to that lib instead of `file_get_contents`)

**Comment by JeroenDeDauw** [comment]
Haha, forgot to tag this :) Now done, almost a year later

**Pull request merged**
